<!-- breadcrumb -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="<?php base_url();?>">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Tracking</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>View Packing Form</span>
        </li>
    </ul>
</div>

<div class="space-4"></div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">View Packing Form</div>
            </div>

            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form method="post" action="" class="form-horizontal" id="form-packing">
                    <input type="hidden" name="<?php echo $this->security->get_csrf_token_name(); ?>" value="<?php echo $this->security->get_csrf_hash(); ?>">
                    <input type="hidden" name="packing_id" value="<?php echo $this->input->post('packing_id'); ?>">
                    <div class="form-body">

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_product_id">Product</label>
                            <div class="col-md-3">
                                <div class="input-group">
                                    <input type="hidden" name="product_id" id="packing_product_id" value="<?php echo $this->input->post('product_id'); ?>" class="form-control">
                                    <input type="text" name="product_code" readonly="" id="packing_product_code" value="<?php echo $this->input->post('product_code'); ?>" readonly="" class="form-control" placeholder="Choose Product">
                                    <!-- <span class="input-group-btn">
                                        <button class="btn btn-success" type="button" onclick="showLovProduct('packing_product_id','packing_product_code')">
                                            <span class="fa fa-search icon-on-right bigger-110"></span>
                                        </button>
                                    </span> -->
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_kg">Weight(Kg)</label>
                            <div class="col-md-3">
                                <input type="text" name="packing_kg" id="packing_kg" value="<?php echo $this->input->post('packing_kg'); ?>" class="form-control required">
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_tgl">Packing Date</label>
                            <div class="col-md-2">
                                <input type="text" name="packing_tgl" id="packing_tgl" value="<?php echo $this->input->post('packing_tgl'); ?>" class="form-control required">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_batch_number">Batch Number</label>
                            <div class="col-md-3">
                                <input type="text" name="packing_batch_number" readonly="" value="<?php echo $this->input->post('packing_batch_number'); ?>" class="form-control" placeholder="Batch Generated By System">
                            </div>
                            <label class="col-md-2 control-label" for="packing_serial">Serial Number</label>
                            <div class="col-md-3">
                                <input type="text" name="packing_serial" readonly="" value="<?php echo $this->input->post('packing_serial'); ?>" class="form-control" placeholder="Serial Generated By System">
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-md-offset-1 col-md-10">
                                <h3>Source Package</h3>

                                <div class="form-group">
                                    <!--
                                    <label class="col-md-3 control-label">Source Material</label>
                                    <div class="col-md-3">
                                        <div class="input-group">
                                            <input type="hidden" name="source_sortir_id" id="source_sortir_id" class="form-control">
                                            <input type="hidden" name="source_product_id" id="source_product_id" class="form-control">
                                            <input type="text" name="source_product_code" id="source_product_code" readonly="" class="form-control" placeholder="Choose Source">
                                            <span class="input-group-btn">
                                                <button class="btn btn-success" type="button" onclick="showLovSortir('source_sortir_id','source_product_code','product_weight_compare','source_product_id')">
                                                    <span class="fa fa-search icon-on-right bigger-110"></span>
                                                </button>
                                            </span>
                                        </div>
                                    </div>


                                    <div class="col-md-3">
                                        <input type="text" id="source_product_weight" name="source_product_weight" class="form-control" placeholder="Weight(Kg)">
                                        <input type="hidden" id="product_weight_compare">
                                    </div>
                                    <div class="col-md-1">
                                        <button class="btn btn-primary" type="button" id="btn-add-source"> Add Source </button>
                                    </div>
                                    -->
                                </div>

                                <table class="table table-bordered table-striped" id="tbl-packing-detail">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Source Material</th>
                                            <th>Weight(Kg)</th>
                                            <th>Farmer</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbody-packing-detail">

                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="button" name="back" id="btn-back" class="btn btn-danger"><i class="fa fa-arrow-left"></i>Back</button>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>

<?php $this->load->view('lov/lov_product_packing.php'); ?>
<?php $this->load->view('lov/lov_sortir.php'); ?>

<script>
    function showLovProduct(id, code) {
        modal_lov_product_show(id,code);
    }

    function showLovSortir(id, code, qty_field, source_product_id) {
        if( $('#packing_product_id').val() == "") {
            swal("Information","Choose product first","info");
            return;
        }
        modal_lov_sortir_show(id, code, qty_field, $('#packing_product_id').val(), source_product_id);
    }
</script>


<script>
    function insertDataRow() {

        var jumlah_baris = document.getElementById('tbl-packing-detail').rows.length;

        var sortir_id = document.getElementById('source_sortir_id').value;
        var product_id = document.getElementById('source_product_id').value;
        var product_code = document.getElementById('source_product_code').value;
        var weight = document.getElementById('source_product_weight').value;

        var tr = document.getElementById('tbl-packing-detail').insertRow(jumlah_baris);
        var tdNo = tr.insertCell(0);
        var tdProduct = tr.insertCell(1);
        var tdWeight = tr.insertCell(2);
        var tdAction = tr.insertCell(3);

        tdNo.innerHTML = jumlah_baris;
        tdProduct.innerHTML = '<input type="hidden" name="pd_id[]"> <input type="hidden" name="sortir_id[]" value="'+ sortir_id +'"> <input type="hidden" name="product_ids[]" value="'+ product_id +'">' + product_code;
        tdWeight.innerHTML = '<input type="hidden" name="weight[]" value="'+ weight +'">' + weight;
        tdAction.innerHTML = '<button type="button" onclick="deleteDataRow(this,null);"><i class="fa fa-trash"></i> Delete </button>';

        document.getElementById('source_sortir_id').value = "";
        document.getElementById('source_product_id').value = "";
        document.getElementById('source_product_code').value = "";
        document.getElementById('source_product_weight').value = "";
        document.getElementById('product_weight_compare').value = "";
    }

    function deleteDataRow(sender,pd_id) {

        if(pd_id != null) {
            $.ajax({
                type: "POST",
                url: '<?php echo WS_JQGRID."agripro.packing_detail_controller/destroy"; ?>',
                dataType : 'json',
                data: {items:pd_id},
                success: function(response) {
                    if(response.success)
                        $(sender).parent().parent().remove();
                }
            });
        }else {
            $(sender).parent().parent().remove();
        }
    }

</script>

<script>

    /**
     * Load data detail
     */

    $(function() {

        $.ajax({
            url: '<?php echo WS_JQGRID."agripro.packing_detail_controller/getDetail"; ?>',
            type: "POST",
            data: {packing_id : <?php echo $this->input->post('packing_id'); ?>},
            success: function (response) {
                $( "#tbody-packing-detail" ).html( response );
            },
            error: function (xhr, status, error) {
                swal({title: "Error!", text: xhr.responseText, html: true, type: "error"});
            }
        });

    });


    $(function() {
        $("#packing_tgl").datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            orientation: 'bottom',
            todayHighlight: true
        });

        $("#btn-back").on('click', function(e) {
            loadContentWithParams('agripro.packing',{});
        });

        $("#btn-add-source").on('click', function(e) {

            var product_id = $('#packing_product_id').val();
            var packing_kg = $('#packing_kg').val();
            var packing_tgl = $('#packing_tgl').val();

            if(product_id == "" || packing_kg == "" || packing_tgl == "") {
                swal('Information','Product, Weight, and Packing Date must be filled first','info');
                return;
            }

            var sortir_id = $('#source_sortir_id').val();
            var packing_weight = $('#source_product_weight').val();
            var packing_weight_compact = $('#product_weight_compare').val();

            if(sortir_id == "" || packing_weight == "") {
                swal('Information','Source Material and Weight must be filled','info');
                return;
            }

            var packing_kg_float = parseFloat(packing_kg);
            var packing_weight_float = parseFloat(packing_weight);
            var packing_weight_compact_float = parseFloat(packing_weight_compact);

            if( packing_weight_float > packing_weight_compact_float ) {
                swal('Information','Weight greater than source weight','info');
                return;
            }

            if( packing_weight_float > packing_kg_float ) {
                swal('Information','Weight greater than packing capacity weight','info');
                return;
            }

            var source_sortir_ids = $('[name="sortir_id[]"]');
            if(source_sortir_ids.length > 0) {
                var error = false;
                $('[name="sortir_id[]"]').each(function(index) {
                    if(sortir_id == $(this).val()) {
                        swal('Information','Oops, we found double source package. choose another source','info');
                        error = true;
                    }
                });
                if(error) return;
            }

            insertDataRow();
        });


        $('#product_weight_compare').on('change', function(e){
            $('#source_product_weight').val(this.value);
        });

        $("#form-packing").submit(function(e) {
            e.preventDefault(); // avoid to execute the actual submit of the form.

            if($("#form-packing").valid() == true){
                var url = '<?php echo WS_JQGRID."agripro.packing_controller/updateForm"; ?>';
                $.ajax({
                    type: "POST",
                    url: url,
                    dataType : 'json',
                    data: $("#form-packing").serialize(),
                    success: function(response) {

                        if(response.success != true){
                            swal('Error',response.message,'warning');
                        }else{
                            loadContentWithParams('agripro.packing',{});
                        }

                    }
                });
            }

        });


    });
</script>